### ISSUE TITLE
4.2 MB of JS gets loaded with 46 total request just for JavaScript

### ISSUE THREAD

**Issue by stefthoen** [getbowtied/product-blocks-for-woocommerce#1]
When I activate this plugin there's an extreme amount of JS that gets loaded from the `wp-includes/js/dist` folder. Is this working as intended?

If I only have WooCommerce active and the Retailer theme active, only 412.87 KB of JS gets downloaded with The Retailer and WooCommerce active.
![woocommerce-retailer](https://user-images.githubusercontent.com/881521/84942995-fdc78e80-b0e3-11ea-8d7c-86b64de959e3.png)

When I activate Product Blocks for WooCommerce, 4.62 MB gets downloaded.
![woocommerce-retailer-product-blocks-for-woocommerce](https://user-images.githubusercontent.com/881521/84943009-04ee9c80-b0e4-11ea-98d5-59a2c97b957a.png)

When I try to Google it, I found this support thread: https://wordpress.org/support/topic/too-many-js-files-from-wp-includes-js-dist/. Could it be that you're doing the same?

**Comment by adrianlbs** [comment]
Hi @stefthoen, thanks for reaching out!

I am just checking in right now to let you know we've started working on it and we'll make sure to improve this with the following update.

**Comment by rthvanesa** [comment]
Hi @stefthoen!

Indeed there was a similar issue with the one you pointed us to. There were some extra libraries destined for the block editor that were also being loaded in the frontend. I want to let you know that we've just released a new version in which focused on the plugin's performance. 

Thanks for reaching out and I hope you enjoy working with our plugin!
