### ISSUE TITLE
Problem with Category display/filter

### ISSUE THREAD

**Issue by marcryu** [getbowtied/product-blocks-for-woocommerce#6]
Hi, 
I love the plugin, it's lightweight and has a lot of potential. However, when I tried to showcase a product slider using "Display by Category", I was presented with only 79 categories to choose from (I have 215). Is there a limit to the product categories? 
Regards
Marc

**Comment by rthvanesa** [comment]
Hi @marcryu,

Thank you for using our plugin! Yes, WooCommerce REST API limits the categories to a maximum of 100 per request. We will look into this issue and try to come up with a solution for it in the next maintenance update.

Have a great day!

**Comment by marcryu** [comment]
Hi Vanesa,

Appreciate the quick response! Looking forward to it.

Thanks!
Marc

**Comment by marcryu** [comment]
Hi Vanesa,

An afterthought, you could also implement a search box for the categories
instead of the pull down menu. May be a good option as well for larger
number of categories. :)

Regards
Marc
